### ISSUE TITLE
Update ED2 singularity container on HPC

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#1031]
- [ ] Update `pecan-model-ed2.sif` 
- [ ] Update `ed2_2.2.0_singularity.sh` 

**KEEP OLD VERSIONS**

**Comment by Aariq** [comment]
- [ ] Talk with Julian

**Comment by Aariq** [comment]
Instructions here: https://hackmd.io/4fZ0EEYgQ06Jf-TTFTliUg
- [x] open issue in ED2 about docker image not getting updated: https://github.com/EDmodel/ED2/issues/355

**Comment by Aariq** [comment]
Oh wait, it's the PEcAn.ED2 docker image that we need, not ED2.  I think I should be able to do this.

**Comment by Aariq** [comment]
Updated container and shell script on HPC.  Re-running a site that previously had a lot of ED2 errors to see if it worked.

**Comment by Aariq** [comment]
- [x] build docker image locally with MODEL_VERSION=git ([tips](https://www.geeksforgeeks.org/docker-arg-instruction/#:~:text=You%20can%20override%20the%20default,will%20see%20the%20updated%20message.))
- [ ] save docker image as tar file ([tips](https://stackoverflow.com/questions/23935141/how-to-copy-docker-images-from-one-host-to-another-without-using-a-repository))
- [ ] move tar file to HPC
- [ ] convert into singularity .sif ([tips](https://stackoverflow.com/questions/52738888/converting-docker-tar-file-into-a-singularity-image))

**Comment by Aariq** [comment]
Notes: https://hackmd.io/@ericrscott/ed2-singularity-update/edit

**Comment by Aariq** [comment]
Done, but didn't work because ED2IN needs updating
