### ISSUE TITLE
Saguaro population dynamics / Peter Breslin

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#1039]
Long time series of population measurements on saguaros. Peter is collecting 6th census. Wants a researcher-facing shiny app to display the dataset to make it more accessible, support data exploration / analysis.

[Proposal draft](https://docs.google.com/document/d/1e-Yl6h8BfsMsxc6eEh68UY0SWlDQa4qcMrcggbNn4jI/edit)

**Comment by Aariq** [comment]
Peter Breslin is off for the summer

**Comment by KristinaRiemer** [comment]
Asking Jessica about this project
