### ISSUE TITLE
Sankey tweaks, update README

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#1083]
<s>- [ ] How to order nodes issue [42](https://github.com/cct-datascience/biofeedback-vis/issues/42), dynamic order from most to least </s>
- [x] issue [43](https://github.com/cct-datascience/biofeedback-vis/issues/43)
- [ ] Update shoutout in README
- [ ] Colors (not diffrentiated enough)

**Comment by jessicaguo** [comment]
Figured out the dummy 8th column!![image.png](https://images.zenhubusercontent.com/5f513e94d41e1d43610542ee/f1d9f9a9-7322-4069-aa0a-a82fee17d2d5)
But now having issues pushing to repo with Kelli as the owner. Will figure out with @Aariq next week. Next steps are to have Kelli review the PR and integrate the changes into the Shiny app.

**Comment by Aariq** [comment]
Looks awesome!  Probably the best thing to do is to just ask/show Kelli how to give you write permission to the repo.  Either that or fork her repo to cct-datascience?
