### ISSUE TITLE
Increase resources on Welsch

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#1131]
Let’s discuss, but we currently have four people using Welsch and should consider making the bulk of our resources available. Min: 8 cores, 32 GB RAM? But we will be doing a lot of highly parallel jobs, so could do more (cores @>=4GB RAM ea. likely more important than total RAM).

**Comment by Aariq** [comment]
Seems like things are running pretty smooth now, but more cores would be nice for parallelization

**Comment by Chris-Schnaufer** [comment]
Working on getting an upgrade to 8cores/32GB
