### ISSUE TITLE
Standardized fish data app / Scott Bonar

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/organization#1136]
proposal: https://docs.google.com/document/d/1UzULGyPVjzvctd8YERn4xKRdv5IWtJ2k/

repo: https://github.com/cct-datascience/AFS_database_code

**Comment by KristinaRiemer** [comment]
- getting viz of user input data with averages working
- long-term (decade) periodic maintenance to keep it working, check every six months
- lots of users - can host on RStudio Connect
- no long-term students/staff who can maintain long-term; Chad is there for two years, Erin is at UC David doing PhD (out Jan - March for field work)
- add issue to incubator board

**Comment by KristinaRiemer** [comment]
[Proposal](https://docs.google.com/document/d/1UzULGyPVjzvctd8YERn4xKRdv5IWtJ2k/edit#)

**Comment by Aariq** [comment]
Held wrap-up meeting but still need to talk about maintenance phase
