### ISSUE TITLE
Enable BETYdb web endpoint on Welsch

### ISSUE THREAD

**Issue by Chris-Schnaufer** [cct-datascience/organization#1182]
After updating the Pecan Docker containers, the BETYdb web interface is no longer available: https://github.com/PecanProject/pecan/issues/3062

Once a solution is available, implement it on Welsch

**Comment by Aariq** [comment]
Looks like this was fixed in a recent PR.  @Chris-Schnaufer, can you update the docker images on Welsch when you get a chance?

**Comment by Aariq** [comment]
Now at http://welsch.cyverse.org:8000/bety

**Comment by Chris-Schnaufer** [comment]
> Now at http://welsch.cyverse.org:8000/bety

Thanks @Aariq!
