### ISSUE TITLE
Fish app map + download

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#1201]
- [x] Continue revising proposal, divide tasks into needs and nice-to-haves
- [x] Communicate to Scott's group
After obtaining fish data and repo permissions:
- [ ] #1225
- [ ] #1226
- [ ] #1227

**Comment by jessicaguo** [comment]
Reviewed Kristina's PR, will meet next week to work through the other issues.

**Comment by dlebauer** [comment]
moved remaining tasks to fish epic
