### ISSUE TITLE
Red squirrel database initial steps

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#1202]
- [x] Review proposal [here](https://docs.google.com/document/d/1KJo1a2Y89Uje8uxYvEC07gaHi3_240jb/edit
- [x] Meet 11/21, take notes [here[(https://docs.google.com/document/d/1DZKy1ezNMdNGeOj0FnjCuHI4WWckLVFXTTcRXwRdaao/edit)

**Comment by jessicaguo** [comment]
Next steps: Vicki will provide MS databases for masterpoints and census, cleaned, to a Box location.

**Comment by dlebauer** [comment]
Met today. Will start w/ schema and data migration as an incubator. Will consult regarding survey migration and web UI

Notes from today: 

![image.png](https://images.zenhubusercontent.com/583f321cb9dc3c622022c169/5519113c-b76c-4140-9742-488ef98f5ca1)

**Comment by Chris-Schnaufer** [comment]
Amazon has updated it's Postgres pricing: within limits (https://aws.amazon.com/rds/free/?loc=ft#Free_Tier), you get 1 year free and charged after that. The [fees]((https://aws.amazon.com/rds/postgresql/pricing/)) apply after 1 year and can be small:  especially if the DB is idled and only spun up when needed. If Matt R's group has an instance already, it may be possible to add a red squirrel db to that instance and keep the costs down as well

**Comment by dlebauer** [comment]
UITS subsidizes even the paid version and will help w/ deployment. Meeting w/ them next week.
