### ISSUE TITLE
Edit FIsh App interface and add plots

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#1227]
Modify Database averages tab, inputs, and subtabs UI
- [x] Combine 3 response variables and display together
 - [x] Leave room for map and plots
 - [x] Meeting 12/7
 - [x] Draft plots

**Comment by jessicaguo** [comment]
Unclear how multiple selections of data types could be used in the plots - emailed for clarification. If only one choice is allowed, may design additional page for data download.

**Comment by jessicaguo** [comment]
Discussed with Kristina, new UI implemented, [PR 5](https://github.com/erinetracy/AFS_database_code/pull/5) has been merged.
