### ISSUE TITLE
Red Squirrel database

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#1233]
- [x] summarize meeting (have David and Chris review)
    - whiteboard notes https://github.com/cct-datascience/organization/1202#issuecomment-1332716214
- [x] Meet with Bret + David + Chris to go over our conclusions

**Comment by Chris-Schnaufer** [comment]
I was looking over the Survey123 site and it looks like the data is stored on the Survey123 server or it can be downloaded as a report (there's also webhooks, but that is probably not desirable): https://doc.arcgis.com/en/survey123/reference/whatissurvey123.htm under the "Analyze results" and "Survey123 components" sections. Depending upon what the workflow is, we may need access/accounts to the website: https://survey123.arcgis.com/
