### ISSUE TITLE
Establish parameters/personnel of extension survey

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#1300]
- [x] Meet 2/1
- [x] Revise [proposal document](https://docs.google.com/document/d/1awxJLdAAo-D4JmINa-m_fv8-NI7OSa9J/edit)

**Comment by Aariq** [comment]
Next meeting same time on Feb 8.  Hold off on starting project until then so Terrace can be coding lead.  Added notes to drive.
