### ISSUE TITLE
ResBaz scheduling

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#1360]
- [x] Attend ResBaz planning meeting
- [x] Wrangle the schedule

**Comment by jessicaguo** [comment]
Initial draft of the [schedule](https://docs.google.com/spreadsheets/d/1uSLx5ntFRoW-1atUDZOrUE0J0eHAqYzfYeG8SiwOyqg/edit#gid=0) now available. Handed over to rest of operations committee to tweak and nudge - as always a living document.

**Comment by KristinaRiemer** [comment]
Does this belong in sprint 2 @jessicaguo?
