### ISSUE TITLE
Teach Git, GitHub, and Intro Data lessons

### ISSUE THREAD

**Issue by diazrenata** [cct-datascience/organization#1580]
- [x] add a floating slide deck + notes on getting help (docs pages, asking questions, reprex, AI). start here: https://cct-datascience.github.io/repro-data-sci/lessons/2-shell/slides.html#/getting-help-3

**Comment by Aariq** [comment]
Increased points because prep + teaching + post-workshop stuff (uploading video, slack engagement, etc.) is a lot
