### ISSUE TITLE
Contribute to Curran NIH proposal

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/organization#1595]
- [x] Figure out who will be named on it
- [x] Update budget justification
- [x] Do NIH biosketch
- [x] Find NSF facilities doc to Kristina (Jessica)
- [ ] Contribute to facilities

**Comment by jessicaguo** [comment]
Here's the facilities statement about CCT from the U'ren proposal:
OTHER RESOURCES
University of Arizona CCT Data Science (UA CCT): The Arizona Experiment Station supports a data science team (UA CCT) with expertise in data management and research computing, including analysis pipelines, software, and data visualization. A key offering is a two-week “incubator” program wherein the researcher and the data scientist work closely together to achieve a well-defined objective, such as a statistical analysis, research software, interactive visualization, or database. Each UA researcher (U’Ren, Tfaily, Guo, graduate students, postdocs) can secure one incubator project that will accelerate their data-intensive research. UA CCT also develops and delivers workshops and short course training on data science and data management topics.  One popular offering is a 5-week (10 sessions) short course on reproducibility and data science, which covers basic shell commands, git and GitHub, and R programming covering both base R and ‘tidyverse’ approaches.
