### ISSUE TITLE
(Fall workshop) summarize post-workshop survey responses

### ISSUE THREAD

**Issue by diazrenata** [cct-datascience/organization#1737]
https://docs.google.com/document/d/1-_WZhgp7ip0-Y3XclceAi-4CPLmiggZnk65dxzYIoWo/edit#heading=h.nt6nousdfma7

**Comment by Aariq** [comment]
draft PR: https://github.com/cct-datascience/repro-data-sci/pull/20

**Comment by Aariq** [comment]
Done: https://cct-datascience.github.io/repro-data-sci/survey_responses.html
