### ISSUE TITLE
Add cultivar information to ardn_mvp.csv

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#233]
the [ardn_mvp.csv](https://github.com/az-digitalag/ardn-terra-ref/blob/master/ardn_mvp.csv) file should include the cultivar name. 

This may be less important if the ardn_mvp.csv is just used for development and the brapi-compliant files are ingested directly by the

**Comment by KristinaRiemer** [comment]
We have a list of other data that it would be good to add on to what we already have, including cultivar, other observations such as canopy height, and management info. This csv just contains the absolute bare minimum needed.

**Comment by dlebauer** [comment]
no longer using ardn_mvp.csv so issue is no longer relevant

https://github.com/cct-datascience/ardn-terra-ref/blob/master/csv_data/mvp/ardn_mvp.csv
