### ISSUE TITLE
First draft of blog post for ag data science resources

### ISSUE THREAD

**Issue by MagicMilly** [cct-datascience/organization#304]
Once feedback is received on the material from Issue #281, write first draft of blog post that will contain this information - to be posted at some point after the website is ready. Twitter curator at this time can also tweet about it.

* [ ] integrate (and acknowldege) the list of resources on campus compiled by Austin: 
[Data_Science_Resources_CALS_2020.pdf](https://github.com/az-digitalag/organization/files/5681701/Data_Science_Resources_CALS_2020.pdf)
* [ ] draft [syllabus](https://hackmd.io/idnlXZFgTp6leQZ5ImhbBw) and [education needs notes](https://hackmd.io/slVMsD4BRTmeTi0mEGhgXg)

**Comment by MagicMilly** [comment]
Moving this to backlog for now since lower priority for wrapping up Q4

**Comment by dlebauer** [comment]
Still need to integrate (and acknowldege) the list of resources on campus compiled by Austin: 
[Data_Science_Resources_CALS_2020.pdf](https://github.com/az-digitalag/organization/files/5681701/Data_Science_Resources_CALS_2020.pdf)
