### ISSUE TITLE
Put bety config in a repository for UA deployment

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#42]
See https://github.com/PecanProject/bety/pull/645

@Chris-Schnaufer The UA specific config file for BETYdb needs to be in a deployment repository with other config files.

@julianpistorius We will need something similar for the UA implementation of the gantry pipeline.

**Comment by julianpistorius** [comment]
@dlebauer Would you say it's related to "Automated deployment of basic pipeline (KR) #44"?

**Comment by dlebauer** [comment]
@julianpistorius yes, but the specific config that we have is for the deployment that Chris has been managing on welsch for the Drone pipeline and PEcAn work; we will need a similar configuration file for the UA gantry pipeline deployment

**Comment by Chris-Schnaufer** [comment]
Related to danforthcenter/sentinel-detection#40
