### ISSUE TITLE
Add content about our group to CALS Faculty Resources page

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#517]
Some of the content in https://docs.google.com/document/d/1EMMMm3WCTCcYEP1_iRLS4l0dys7z0uL5i39qIzcYxgY/edit#heading=h.xiy4g5g2w3p7

Could probably be added to https://research.cals.arizona.edu/

_Originally posted by @dlebauer in https://github.com/az-digitalag/organization/issues/336#issuecomment-854061867_

**Comment by Aariq** [comment]
Document no longer exists
