### ISSUE TITLE
Volatility Calculation Database Automation

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/organization#550]
[Proposal](https://docs.google.com/document/d/1rcBuw8w64trNycilRvB26bypcjDiqQ821rNtIEAW9pM/edit)

**Comment by Aariq** [comment]
Manuscript in prep for Frontiers in Microbiology

**Comment by Aariq** [comment]
Manuscript submitted

**Comment by Aariq** [comment]
Got reviews back

**Comment by Aariq** [comment]
Accepted, proofs submitted
