### ISSUE TITLE
RainManSR Open Data Makeover

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#552]
For Bill Smith (SNRE) and Joel Biederman (USDA ARS, Tucson) and the entire RainManSR project
Project scope of work [here](https://docs.google.com/document/d/1v1przz6eblqULIdgXxRbZWjEkBI6ZqivEd9p77v7IiQ/edit)
[Folder](https://drive.google.com/drive/u/2/folders/1VBYCMFPMR1nS6YK_faxL7jjfWvrXCgY7) of powerpoints

**Comment by KristinaRiemer** [comment]
@jessicaguo is this considered finished now?

**Comment by jessicaguo** [comment]
Yes, it is!

**Comment by KristinaRiemer** [comment]
Woot! First one that can be moved into the "Complete" pile!
