### ISSUE TITLE
Visualizing high dimension VOC timeseries

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#555]
For Laura Meredith (SNRE) and Jana U'Ren (Biosystems Engineering)
Project proposal [here](https://docs.google.com/document/d/1O80hTwd0gsmSXsy-lTBHHtyqoQ223Kj423Ip-W7_DPs/edit)

**Comment by KristinaRiemer** [comment]
Asked Jessica about the status of this
