### ISSUE TITLE
Update drones.arizona.edu website

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#580]
- [x] link to https://research.cals.arizona.edu/unmanned-aerial-vehicles-uavs
- [x] add calendar to home page
* Resources for getting started
  - [ ] Software (ESRI, DPP, Agisoft, other ... not a comprehensive list, but how to use at UA, who is using it)
  - [ ] Computing resources
  - [ ] Standards, Protocols
- [ ] add recent news to home page
- [ ] get people to add posts, people pages

**Comment by Aariq** [comment]
@Chris-Schnaufer can this be closed?

**Comment by Chris-Schnaufer** [comment]
Yes. Closing as obsolete
