### ISSUE TITLE
Add publications page to group website

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/organization#756]

**Comment by Aariq** [comment]
Idea: create a public, closed-membership Zotero library.  Example: https://www.zotero.org/groups/4775341/plant_phenology

**Comment by Aariq** [comment]
#### Publications page options:

1. Link to group google scholar page from menu bar item
    - E.g.: https://scholar.google.com/citations?user=HWhxBY4AAAAJ&hl=en
    - Pros: track citation metrics, easy to find and add papers
    - Cons: another thing to update, visually uninteresting
2. Link to a Zotero library from menu bar item
    - E.g.: https://www.zotero.org/groups/4775341/plant_phenology/items
    - Pros: easy for us to add papers.  People could subscribe to our library through Zotero (not sure why they'd want to though).
    - Cons: another thing to update, visually uninteresting
3. Use "Publications" content type
    - E.g.: https://datascience.cals.arizona.edu/publication/brapi-application-programming-interface-plant-breeding-applications (imagine these on a single page like the new incubator page)
    - Pros: potential to be visually interesting
    - Cons: Probably need Hannah to create a new "view" for the content type "Publication". "Publication" content type probably also needs editing. The website is annoying to edit.

I think we need to decide if this needs to be just a list of publications or something more annotated (e.g. https://terraref.org/news/publications).  If it just needs to be a list, then setting up a Google Scholar page for the group is probably best.

**Comment by Aariq** [comment]
David, Eric, Kristina vote for group Google Scholar page

**Comment by Aariq** [comment]
Additional "cons" for Google Scholar: must be created with a Google account and we can't get one for cct-datascience@arizona.edu or cct-datascience-admins@arizona.edu.  Would need to create cct-datascience@gmail.com

**Comment by Aariq** [comment]
Created cct.datascience@gmail.com as our google account.  Created profile here: https://scholar.google.com/citations?view_op=list_works&hl=en&user=gpMLNHQAAAAJ.  Will work on adding publications.
