### ISSUE TITLE
Refine BRIDGES workshop curriculum

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/organization#892]
We need to pick out some of the specific lessons we're using, choose who is teaching what, and run through material.

**Comment by jessicaguo** [comment]
Bridges material for sping and fall workshop planned, will be using intro to shell and intro to R/Rstudio materials from DC Genomics. Datasets obtained. 

Fall workshop will feature using folder of data/scripts,/figures generated this time to talk about file organization, research compendia, and git/GitHub. 

For two followups, first can be intro to HPC from Derrick or Chris, second can be a showcase of their own project folders turned into reserach compendia and repositories on GH. 

To do for next sprint: Run through the full lesson with data at least once, read up on terms and file formats .
