### ISSUE TITLE
Run DSSAT with TERRA REF ACEB & (more) completed DOME

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/organization#927]
David started the DOME at the in person event at UF, we might need to get with Cheryl to complete it.

**Comment by dlebauer** [comment]
TODO:
* aceb_test.csv should have 
   * [ ] a field EXNAME with a value "TERRAREF-----S4"
   * [ ]  a field CRID with value "SGG"

**Comment by KristinaRiemer** [comment]
[Getting closer](https://github.com/cct-datascience/ardn-terra-ref/pull/7#issuecomment-1145316193).
