### ISSUE TITLE
Investigate CyVerse VICE as PEcAn dev environment

### ISSUE THREAD

**Issue by julianpistorius** [cct-datascience/organization#93]
Potential roadblocks and things to investigate:

- 48 hour timeout 
  - Feature not a bug? Meaning: Getting used to working from a clean container and then programmatically adding (patching) the environment might give more stability, and will be more reproducible (assuming the code & test data are persisted between runs)
- Getting file data to the container
  - VICE/DE already lets you stage data
- Getting access to a remote PostgreSQL database
  - Script that sets up an SSH tunnel to a DB server using CyVerse credentials?
  - Or just use https://github.com/Oslandia/pglite and use a local database pre-populated with a snapshot of a database.
- Ensuring output data from the container is persisted
  - _Should_ end up in analyses folder 
- Committing & pushing to GitHub from VICE
  - OK to store credentials on VICE?
  - Should also be possible to do SSH agent-forwarding
  - Even better would be a way to use R bindings to the GitHub API and then ask the user to generate a dedicated personal GitHub API key, and prompt them to enter it when launching the  VICE environments: https://github.com/cscheid/rgithub
  - Or ask the user to create a GitHub deployment key. They can then provide this as input when launching the VICE app. See the Continuous Analysis documentation for how they use this key: https://greenelab.github.io/continuous_analysis/

**Comment by julianpistorius** [comment]
@kimberlyh66 not sure if you're interested in helping with this.

**Comment by KristinaRiemer** [comment]
Started [notes on HackMD(https://hackmd.io/ms-iQBtnQD-MfbMdO6TbjA) @julianpistorius
