### ISSUE TITLE
Prepare data quality validation workshop for August

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#950]
* [x] research: get ideas from UCSB meetup on topic
* [x] refine notes for the workshop
* [x] put together workshop materials (Rmd workbook, data, etc.)
* [ ] advertise
    * [x] https://datascience.cals.arizona.edu/services-overview/workshops
    * [x] https://datascience.arizona.edu/calendar
    * [ ] email listserv
    * [ ] other places?

**Comment by Aariq** [comment]
PR draft: https://github.com/cct-datascience/CALS-workshops/pull/15
