### ISSUE TITLE
Scope out plan for Bio Feedback Proposal

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#954]
* [x] [Read proposal](https://docs.google.com/document/d/14OL0ACZvaSXyBVMY_aaPZR5MSuXbMVegEhk6sPkc3Ec/edit)
* [ ] make sure outcomes are clearly defined and in scope
* [x] ask for clarification as needed
* [x] Make a repo
~~* [ ] get some test data~~
~~* [ ] define implementation details, create new issues as needed~~

**Comment by Aariq** [comment]
https://github.com/cct-datascience/biofeedback-vis

**Comment by jessicaguo** [comment]
I thought the outcomes were clearly laid out, but had some questions on the execution of the interactivity. Setting up a meeting next week to discuss with Kelli.

**Comment by jessicaguo** [comment]
Meeting scheduled for July 5. Will coordinate data transfer during the meeting.
