### ISSUE TITLE
Update ARDN data on NAL

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#959]
* [x] review https://github.com/cct-datascience/ardn-terra-ref/pull/8
* [x] Create clones for existing Season 6 and update with new files
  * [x] update brapi json files
     * [x] merge events.json in terraref/brapi
     * [x] create separate events files in ardn terraref
  * [x] upload four CSV tables in csv_data folder
  * [x] upload SC2 file in dssat_files folder
* [x] write in description how these can be used to generate model inputs.
* [x] Create a release https://github.com/cct-datascience/ardn-terra-ref/releases/new
* [x] upload zip file archive to ADC

Maybe .... model specific stuff in a separate dataset (perhaps outside scope of project). Do we need to do that? Maybe sufficient to archive repository.

Files:
- [x] events_6000000010.json     
- [x] germplasm_6000000010.json  
- [x] observations_6000000010.json
- [x] study_6000000010.json
- [x] events_6000000034.json     
- [x] germplasm_6000000034.json
- [x] observations_6000000034.json
- [x] study_6000000034.json

**Comment by KristinaRiemer** [comment]
Data to add to ADC: 

- Raw Brapi JSON files (4)
- CSV version of files (4)
- SC2

And maybe the AgMIP ZIP from the csv + SC2? Everything else downstream probably doesn't need to go in there, especially not the DSSAT-specific files. 

Cheryl did say something about generating a SC3, but I don't know what that entails.

**Comment by dlebauer** [comment]
Complete and submitted for review. Draft release is here: https://github.com/cct-datascience/ardn-terra-ref/releases/tag/v1.0
