### ISSUE TITLE
Prototype biological feedback dashboard

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#974]
- [x] Meet with Kelli 7/5
- [x] Obtain and understand data
- [x] Prototype (draw out) dashboard versions
- [x] Build Shiny app

**Comment by jessicaguo** [comment]
Nice work! The only difficulty in running was installing ggsankey and updating dependencies, but I'm not sure that friction can be totally removed. 

One idea: If a person selects a subset of a category, e.g. the Domain of Diabetes, could the rest of the input boxes be updated to the limited set of nodes associated with that domain? That might make the fully listed input UI less intimidating/long.

**Comment by Aariq** [comment]
That's a great idea and might be worth figuring out if we decide to stick with this interface instead of clicking on the plot itself.  I'll open an issue to remind us.

**Comment by Aariq** [comment]
draft here: https://viz.datascience.arizona.edu/biofeedback_sankey/
