### ISSUE TITLE
Soil moisture GAMs and Biederman review

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#977]
- [x] Review [documentation/repo](https://github.com/cct-datascience/Rainman-swp) (Eric)
- [ ] Collaborate on GAMs and update swc2swp() function
   - [here is a first pass](https://gist.github.com/dlebauer/2be0dbdad33c1fcf67a86f97390a284d) that is nowhere near close  
- [ ] Update documentation (Jessica)

**Comment by Aariq** [comment]
Oh, this might also be useful if any extrapolation beyond data is happening: https://fromthebottomoftheheap.net/2020/06/03/extrapolating-with-gams/
