### ISSUE TITLE
Hummingbird network database / Gaby Samaniego

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#983]
Automated and reproducible way to add new field data (from app and paper forms) to database and create Shiny dashboard to view, filter, and download the data. 
[Notes](https://docs.google.com/document/d/1kRUALJlaJd3RSkhyo0Up6AZy_AhBHP9cPAmu1izsujc/edit)

**Comment by KristinaRiemer** [comment]
No longer pursuing this project due to data access limitations.
