### ISSUE TITLE
Run Setaria simulations at transect sites

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/organization#986]
- [x] Slack Julian about permissions on Welsch
- [x] Merge Kristina's PR
- [ ] Run the rest of the sites with site-relevant PFTs and weather
- Ask German if he wants to meet and work through any of this together.

**Comment by Aariq** [comment]
I can't do this in the most correct way until I get the permissions issues on Welsch worked out.

**Comment by Aariq** [comment]
Notes:
- Need write access to `data/dbfiles/posterior`?
- Check Vcmax posteriors with @dlebauer or @KristinaRiemer—they don't look right to me.
- How to deal with lack of convergence in meta analysis?

**Comment by Aariq** [comment]
Yeah, I think there's a problem with the priors for vcmax.  This is from one of Kristina's runs:
![Screen Shot 2022-07-21 at 1 06 27 PM](https://user-images.githubusercontent.com/25404783/180272655-98f5cacc-2c35-4f90-85a6-dc6440fc2ca3.png)

I don't know what 'approx' is, but the prior seems bounded incorrectly

**Comment by dlebauer** [comment]
"approx" is a parameterized distribution fit to the posterior, e.g. a normal with mean and sd of the MCMC samples. Next step is to figure out why the prior and data are inconsistent. 

Sometimes this points to an error in the data - some examples include 
- it entered with the correct units, 
- conversions done incorrectly
- With Vcmax, there is a leaf temperature covariate that is used in conversion; this should be correct


It could also be an issue with the prior - too narrow, built with too few samples, estimated from traits of wild plants not applicable to crops, or measurements from a growth chamber or greenhouse will be very different. This should be accounted for in the model with the greenhouse fixed effect, but might not be estimated if there is only data from chambers

Which PFT is this? If it is Setaria, I'd be curious if we have encountered this before, if not why not. Would be good to check in with @jessicaguo who I think entered many of the Setaria Vcmax data.

**Comment by Aariq** [comment]
This is SetariaWT.  It looks like this in all of a haphazard sample of the runs in /data/tests/
